### ISSUE TITLE
New release, please

### ISSUE THREAD

**Issue by erikgb** [Ontotext-AD/puppet-graphdb#17]
I am in desperate need of a release containing [this commit](https://github.com/Ontotext-AD/puppet-graphdb/commit/ffbf04c30d32d90b5ccf7c978c2ebfa85f4d85c5) to use this Puppet module for a SSL/TLS enabled GDB.

**Comment by rdstn** [comment]
We have just performed a release, [0.5.0](https://github.com/Ontotext-AD/puppet-graphdb/releases/tag/0.5.0). Please notify us if you have any trouble using it.
